apiVersion: v1
kind: Service
metadata:
  name: zomato-service
spec:
  selector:
    app: zomato
  type: NodePort
  ports:
    - protocol: TCP
      port: 3001          # external service port (can stay 3001)
      targetPort: 3000    # must match containerPort/app port inside pod
      nodePort: 32001
